# Generated by Django 2.2.2 on 2019-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_conv', models.TextField()),
                ('bot_conv', models.TextField()),
            ],
        ),
    ]
